---

- name: Install tools for Windows artifacts
  apt:
    pkg:
       - missidentify # search for windows PEs
       - tofrodos # from DOS; to DOS LF conversion
       - winregfs # FUSE-based FS driver that enables accessing Registry
       - reglookup # read windows registry elements and print them out to stdout as csv
       - vinetto # tool to view thumbs.db
       - libemail-outlook-message-perl # conversion of .msgs
       - libevtx-utils # conversion of evtx with evtxexport, etc.
  become: yes

- name: Include regripper
  include: regripper.yml

- name: Include FAT, MFT, INFO2 parsers
  include: win_fs_parsers.yml
