---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: no
    update_cache: yes


- name: Install log parsing tools
  apt:
    pkg:
       - coreutils # all the core Unix goodess!
       - parallel # process standard input in parallel
       - csvkit # whole bunch of tools for working with csv
       - jq # Work with JSON
       - python3-evtx # evtx_dump, ...
  become: yes

- name: Install network exploration tools
  apt:
    pkg:
       - geoip-bin
       - dnsutils
       - whois
       - nmap
  become: yes

- name: Clone helpful dfir scripts repo
  git:
    repo: https://github.com/dfir-scripts/shellscripts
    dest: /usr/local/share/dfir-scripts
    force: yes

- name: Find all files in ~/commands
  find:
    paths: /usr/local/share/dfir-scripts
    patterns: "*.sh"
  register: find

- name: Make dfir-scripts executable
  become: yes
  file:
    path: "{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  "0755"
    state: touch
  with_items: "{{ find.files }}"

- name: Create symlinks in /usr/local/bin for dfir-scripts
  become: yes
  file:
    src: "{{ item.path }}"
    dest: "/usr/local/bin/{{ (item.path | basename | splitext)[0] }}"
    state: link
    owner: "{{ ansible_user }}"
    mode: "0755"
  with_items: "{{ find.files }}"
