---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: no
    update_cache: yes

- name: Install forensics packages
  apt:
    pkg:
    - netcat
    - wireshark
  become: yes


- name: Install python package of unfurl, which dissects and parses ULRs
  pip:
    name: unfurl
    executable: pip3
