---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: no
    update_cache: yes

- name: Install forensics packages
  apt: pkg={{ item }}
  state: present
  become: yes
  with_items:
    - netcat
    - wireshark


