---

- name: Install carving and data recovery utilities
  apt:
    pkg:
       - foremost
       - scalpel # tsk's carver
       - ext4magic # recover ext3 and ext4 files
       - extundelete # recover deleted files from ext journal
       - ntfs-3g # ntfs
       - scrounge-ntfs # rescue data from corrupted NTFS partitions
       - testdisk  # contains photorec also
  become: yes

- name: Kessler parser import
  include: ./kessler_parser.yml

- name: Install hashing utils
  apt:
    pkg:
       - hashrat # directory, recursive hashing
       - hashdeep # fuzzy hashing
       - rhash # wide range of hashsum
       - ssdeep # content aware
  become: yes

- name: Install content utils
  apt:
    pkg:
       - binwalk
       - p7zip-full  # 7zip
       - shed # Hex viewer
       - sqlitebrowser
       - mpack # unpacking of .emls
       - pcre2-utils # perl compatible grep syntax (pcre2grep...)
  become: yes
