---
- name: Install chromium
  apt:
    pkg:
     - chromium
     - chromium-l10n

- name: Install thunderbird
  apt: 
    pkg:
      - thunderbird 

- name: Install scanning drivers and utils
  apt:
    pkg:
      - sane
      - sane-utils
      - libsane
      - img2pdf # for actual scanning

- name: Install adf2pdf
  pip:
    name:
      - adf2pdf
    executable: pip3
  become: yes  # scanner is accessible as root

- name: Install latex
  apt:
    pkg: 
      - texlive-full
      - texlive-font-utils
      - texlive-fonts-extra
      - biber

- name: Install Xmind
  apt:
   deb: https://dl3.xmind.net/XMind-for-Linux-amd-64bit-11.0.1-202106220606.deb
