---
- name: Install python3 packages
  apt:
    pkg:
      - python3
      - python3-pip
    state: present
  become: yes
  tags:
    - python3


- name: Install jupyter
  pip:
    name:
    - jupyterlab
    - notebook
    executable: pip3
