---
- name: Install python3 packages
  apt:
    pkg:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: yes
  tags:
    - python3

- name: Install wheel
  pip:
    name:
      - wheel
    executable: pip3
  become: yes  # scanner is accessible as root
