---

- name: Download Gary Kesslers bsparser
  get_url:
      url: https://www.garykessler.net/software/bsparser_v3.1.zip
      dest: /tmp/
      checksum: sha1:e210994cebdffbe079f934de1ccd9bb2229a3619

- name: Unarchive BSParser .zip-file
  unarchive:
    src: /tmp/bsparser_v3.1.zip
    dest: /tmp/
    remote_src: yes

- name: Copy bsparser to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/bsparser.pl"
    dest: "/usr/local/bin/bsparser"
    mode: "0775"
    owner: "{{ ansible_user }}"

- name: Download Gary Kesslers FAT directory parser
  get_url:
      url: https://www.garykessler.net/software/dirparser_v2.1.zip
      dest: /tmp/
      checksum: sha1:9d15d4a6319ac60fc925b60010445b7b75cb40e8

- name: Unarchive dirparser .zip-file
  unarchive:
    src: /tmp/dirparser_v2.1.zip
    dest: /tmp/
    remote_src: yes

- name: Copy dirparser to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/dirparser.pl"
    dest: "/usr/local/bin/bsparser"
    mode: "0775"
    owner: "{{ ansible_user }}"

- name: Download Gary Kesslers GPT parser
  get_url:
      url: https://www.garykessler.net/software/gptparser_v1.4beta.zip
      dest: /tmp/
      checksum: sha1:5fe142bf783ffdab829291a91a46c5095fa2403a

- name: Unarchive gpt .zip-file
  unarchive:
    src: /tmp/gptparser_v1.4beta.zip
    dest: /tmp/
    remote_src: yes

- name: Copy gptparser to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/gptparser.pl"
    dest: "/usr/local/bin/gptparser"
    mode: "0775"
    owner: "{{ ansible_user }}"

- name: Download Gary Kesslers MBR parser
  get_url:
      url: https://www.garykessler.net/software/mbrparser_v2.1.zip
      dest: /tmp/
      checksum: sha1:b6cee0e7eb35a0a499d1d0e18bd78dd719bcc6af

- name: Unarchive mbrparser .zip-file
  unarchive:
    src: /tmp/mbrparser_v2.1.zip
    dest: /tmp/
    remote_src: yes

- name: Copy mbrparser to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/mbrparser.pl"
    dest: "/usr/local/bin/mbrparser"
    mode: "0775"
    owner: "{{ ansible_user }}"

- name: Download Gary Kesslers MFT parser
  get_url:
      url: https://www.garykessler.net/software/mftparser_v2.1.zip
      dest: /tmp/
      checksum: sha1:abc17f54c64ae6422c33e1f2d04658a0d2d82b2a

- name: Unarchive mftparser .zip-file
  unarchive:
    src: /tmp/mftparser_v2.1.zip
    dest: /tmp/
    remote_src: yes

- name: Copy mbrparser to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/mftparser.pl"
    dest: "/usr/local/bin/mftparser"
    mode: "0775"
    owner: "{{ ansible_user }}"

- name: Download Gary Kesslers MFT parser
  get_url:
      url: https://www.garykessler.net/software/info2parser_v1.4.zip
      dest: /tmp/
      checksum: sha1:04d1e967a19c0fb30ce75bab3284826c321e93aa

- name: Unarchive info2parser .zip-file
  unarchive:
    src: /tmp/info2parser_v1.4.zip
    dest: /tmp/
    remote_src: yes

- name: Copy mbrparser to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/info2parser.pl"
    dest: "/usr/local/bin/info2parser"
    mode: "0775"
    owner: "{{ ansible_user }}"
