---
- name: Check, whether the /usr/bin/emacs exists
  stat:
    path: /usr/bin/emacs
  tags: emacs
  register: emacs_result

- name: Update apt-cache
  become: yes
  apt: update_cache=yes
  when: emacs_result.stat.exists == False

- name: Install emacs from package archives
  become: yes
  apt:
    pkg:
      - emacs
  tags: packages, emacs
  when: emacs_result.stat.exists == False

- name: Recursively change ownership of /usr/local/src
  ansible.builtin.file:
    path: /usr/local/src
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    
- name: Clone emacs repo
  become: yes
  become_user: "{{ ansible_user }}"
  git:
    repo: git://git.savannah.gnu.org/emacs.git
    dest: /usr/local/src/emacs
    depth: 1
    update: yes
    version: master

- name: Install dependencies for emacs compilation
  become: yes
  apt:
    pkg:
      - stow
      - build-essential
      - libx11-dev
      - xaw3dg-dev
      - libjpeg-dev
      - libpng-dev
      - libgif-dev
      - libtiff-dev
      - libncurses5-dev
      - libxft-dev
      - librsvg2-dev
      - libmagickcore-dev
      - libmagick++-dev
      - libxml2-dev
      - libgpm-dev
      - libotf-dev
      - libm17n-dev
      - libgconf2-dev
      - libgnutls28-dev
      - libjansson4
      - libjansson-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libgccjit-10-dev
      - texinfo
  tags: packages, emacs
  when: emacs_result.stat.exists == False

- name: Compile emacs
  become: yes
  ansible.builtin.shell:
    cmd: export CC=/usr/bin/gcc-10 CXX=/usr/bin/gcc-10 && ./autogen.sh && ./configure --with-mailutils --with-json --with-x-toolkit=gtk3 --with-xwidgets --with-modules --with-native-compilation --with-gnutls --with-jpeg --with-png --with-rsvg --with-tiff --with-wide-int --with-xft --with-xml2 --with-xpm && make -j16 && make install
    chdir: /usr/local/src/emacs

- name: Install dependencies for emacs operation from package archives
  become: yes
  apt:
    pkg:
      - find
      - ripgrep
      - mu4e
      - isync
      - libgmime-3.0-dev
      - libxapian-dev
      - pandoc
      - cmake
  tags: packages, emacs
  when: emacs_result.stat.exists == False