---
- name: Check, whether the /usr/bin/emacs exists
  stat:
    path: /usr/bin/emacs
  tags: packages, emacs
  register: emacs_result

- name: Remove old .emacs.d
  file:
    path: /home/{{ ansible_user }}/.emacs.d
    state: absent
  become: yes
  when: emacs_result.stat.exists == True
  
- name: Install emacs package
  apt: 
    pkg:
      - emacs-gtk
      - ripgrep
      - fd-find
      - ccls # for Language Server Protocol for C/C++
  tags: packages, emacs

- name: Clone doom-emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: /home/{{ ansible_user }}/.emacs.d
    depth: 1
    force: yes

- name: Change permisions of .emacs.d
  file:
    path: /home/{{ ansible_user }}/.emacs.d
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  become: yes

- name: Install additional packages 
  pip:
    name:
    - autopep8
    - flake8


