---
- name: Check, whether the /usr/bin/emacs exists
  stat:
    path: /usr/bin/emacs
  tags: packages, emacs
  register: emacs_result

- name: Update apt-cache
  apt: update_cache=yes
  tags: packages, python
  when: emacs_result.stat.exists == False

- name: Install packages needed for compiling
  apt: pkg={{ item }}
  with_items:
    - emacs-gtk
    - ccls # for Language Server Protocol for C/C++
  tags: packages, emacs
  when: emacs_result.stat.exists == False

- name: Cloning doom-emacs
  git:
    repo=https://github.com/hlissner/doom-emacs
    dest=/home/{{ ANSIBLE_USER }}/.emacs.d
    depth=1

- name: Add doom commands to $PATH 
  copy:
    dest: /home/{{ ANSIBLE_USER }}/.emacs.d/bin/
    content: 'PATH=$PATH:{{ my_custom_path_var }}'
    
- name: Install additional packages 
  pip:
    name:
    - autopep8
    - flake8


