---
- name: Install zsh, git, powerline, tmux
  apt: pkg={{ item }}
  with_items:
    - git
    - zsh
    - tmux
    - powerline
  register: installation

- name: set default shell for user
  user:
    name: '{{ ansible_user }}'
    shell: /bin/zsh

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest={{ OMZSH_DIR }}
  when: installation is success
  register: cloning

- name: Creating new ~/.zshrc
  copy:
    src=zshrc
    dest=/home/{{ ansible_user}}/.zshrc
  when: cloning is success

- name: Cloning zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest={{ OMZSH_CUSTOM }}/plugins/zsh-autosuggestions
  when: installation is success
  register: cloning

- name: Upload .tmux.conf
  copy:
    src=tmux.conf
    dest=/home/{{ ansible_user }}/.tmux.conf
  when: cloning is success

  #- name: Backing up existing ~/.zshrc
   #  shell: if [ -f /home/{{ ansible_user }}/.zshrc ]; then mv /home/{{ ansible_user }}/.zshrc{,.orig}; fi
   #  when: installation|success
   #  sudo: no

   #- name: Copy sample config from git repo to local
#  copy: remote_src=True src={{ OMZSH_DIR }}/templates/zshrc.zsh-template dest=/home/{{ ansible_user }}/.zshrc
