- name: Install base packages
  apt:
    pkg:
     - locales
     - build-essential
     - acl
     - ntp
     - git
     - supervisor
     - cifs-utils
     - libnotify-bin
  become: yes
  tags:
    - packages

#- name: Create user
#  user:
#    name: user01
#    state: present
#    createhome: yes
#    groups: "sudo"
#    # Has to be defined in inventory
#    password: "{{ password }}"

#- name: Create .ssh folder
#  file:
#    path: /home/user01/.ssh/
#    state: directory
#    mode: 0755
