---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: False
    update_cache: yes

- name: Install imaging tools
  apt:
    pkg:
       - pv  # monitor the progress of data through a pipe
       - dc3dd
       - dcfldd
       - ewf-tools
       - gddrescue
       - guymager
       - hdparm
       - tableau-parm  # to to interact with tableau writeblockers
  become: yes

- name: Install image utils
  apt:
    pkg:
       - afflib-tools
       - kpartx
       - libafflib-dev
       - libewf-dev
       - libfuse-dev
       - pciutils
       - qemu
       - qemu-utils
       - smartmontools
       - usbutils
       - xmount
  become: yes

- name: Install pyaff4
  pip:
    name: pyaff4
    executable: pip3

- name: Download aff4.py logical imager
  get_url:
    url: https://raw.githubusercontent.com/aff4/pyaff4/master/aff4.py
    dest: /usr/local/bin/aff4
    mode: '0775'

- name: Ensure shebang exists in aff4.py
  ansible.builtin.lineinfile:
    path: /usr/local/bin/aff4
    insertbefore: BOF
    line: "#!/usr/bin/python3"
    state: present
