---

- name: Install file identifiers
  apt:
    pkg:
      - file
  become: yes

#
#- name: Download TrID
#  get_url:
#    url: http://mark0.net/download/trid_linux.zip
#    dest: /tmp/trid_linux.zip
#    # TODO checksum: sha256:
#    timeout: 1500
#
#- name: Create /usr/local/share/trid
#  file:
#    path: /usr/local/share/trid
#    state: directory
#    owner: "{{ ansible_user }}"
#    mode: "0755"
#
#- name: Extract trid into /usr/local/share/trid
#  unarchive:
#    src: /tmp/trid_linux.zip
#    dest: /usr/local/share/trid/
#    remote_src: yes
#    list_files: yes
#  become: yes
#  become_method: sudo
#  register: archive_contents
#
#- name: Download TrID definitions
#  get_url:
#    url: http://mark0.net/download/triddefs.zip
#    dest: /tmp/triddefs.zip
#    # TODO checksum: sha256:
#    timeout: 1500
#
#- name: Extract trid into /usr/local/share/trid
#  unarchive:
#    src: /tmp/triddefs.zip
#    dest: /usr/local/share/trid/
#    remote_src: yes
#    list_files: yes
#  become_method: sudo
#
#- name: Make /usr/local/share/trid/trid executable
#  file:
#    path: /usr/local/share/trid/trid
#    state: touch
#    owner: "{{ ansible_user }}"
#    mode: u+rw,g+rx,o+rx
#
#- name: Create symlink in /usr/local/bin for /usr/share/trid/trid
#  become: yes
#  file:
#    src: "/usr/local/share/trid/trid"
#    dest: /usr/local/bin/trid
#    state: link
#    owner: "{{ ansible_user }}"
#    mode: "0755"
#