---

- name: Install openjdk11
  apt:
    pkg:
      - openjdk-11-jdk
  become: yes

- name: Download Ghidra
  get_url:
    url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.1_build/ghidra_10.0.1_PUBLIC_20210708.zip
    dest: /tmp/ghidra.zip
    checksum: sha256:9b68398fcc4c2254a3f8ff231c4e8b2ac75cc8105f819548c7eed3997f8c5a5d
    timeout: 1500

- name: Extract Ghidra into /usr/local/share/ghidra*
  unarchive:
    src: /tmp/ghidra.zip
    dest: /usr/local/share/
    remote_src: yes
    list_files: yes
  become: yes
  become_method: sudo
  register: archive_contents

- name: Create symlink in /usr/local/bin for /usr/share/ghidra*/ghidraRun
  become: yes
  file:
    src: "/usr/local/share/{{ archive_contents.files[0] }}/ghidraRun"
    dest: /usr/local/bin/ghidra
    state: link
    owner: "{{ ansible_user }}"
    mode: "0755"

- name: Download IDA Pro Keybindings for Ghidra
  get_url:
    url: https://raw.githubusercontent.com/nullteilerfrei/reversing-class/master/ghIDA.kbxml
    dest: /usr/local/share/{{ archive_contents.files[0] }}/ghIDA.kbxml
    mode: '0744'
