---

- name: Install yara requirements from apt
  become: yes
  package:
    name: "{{ yara_apt_requirements }}"
    state: latest

- name: Extract yara into /tmp
  unarchive:
    src: https://github.com/VirusTotal/yara/archive/v{{ yara_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
  tags: packages, yara

- name: Bootstrap yara
  become: yes
  shell: ./bootstrap.sh chdir=/tmp/yara-{{ yara_version}}

- name: Configure yara
  shell: ./configure --enable-magic chdir=/tmp/yara-{{ yara_version}}
  tags: packages, yara

- name: Make yara
  shell: make chdir=/tmp/yara-{{yara_version}}
  tags: packages, python

- name: Install yara
  shell: make install chdir=/tmp/yara-{{ yara_version}}
  become: yes
  become_user: root
  tags: packages, python

- name: Install python package of yara
  pip:
    name: yara
    executable: pip3

- name: Cleanup yara installation files
  become: yes
  file: path=/tmp/{{ item }} state=absent
  with_items:
    - /tmp/yara-{{ yara_version }}
    - /tmp/yara-{{ yara_version }}.tar.gz
